### ISSUE TITLE
Add meta-id service

### ISSUE THREAD

**Issue by MrTibbles** [jaakmusic/jaak-api#1]
[meta-id graphql service](https://github.com/meta-network/go-meta/tree/master/identity)

- [ ] meta-id graphql schema
- Queries
  - [ ] `identity(id: String,owner: String): [Identity]!`
  - [ ] `claim(issuer: String,subject: String,claim:String,signature:String,id:String): [Claim]!`
- Mutations
  - [ ] `createIdentity(username: String, owner: String,signature:String): Identity`
  - [ ] `createIdentity(username: String, owner: String,signature:String): Identity`
